export const AUTH_REDUX_CONSTANTS = {
    ON_CHANGE_AUTH_INPUT_VALUE: 'ON_CHANGE_AUTH_INPUT_VALUE',
    CHECK_CREDENTIALS: 'CHECK_CREDENTIALS',
    LOGOUT_USER_ACTION: 'LOGOUT_USER_ACTION',
    CHANGE_AUTH_STATUS: 'CHANGE_AUTH_STATUS',
}