export const AUTH_REDUX_CONSTANTS = {
    ON_CHANGE_AUTH_INPUT_VALUE: 'ON_CHANGE_AUTH_INPUT_VALUE',
    CHECK_CREDENTIALS: 'CHECK_CREDENTIALS',
    SET_LOGGED_IN_USER_NAME: 'SET_LOGGED_IN_USER_NAME',
    LOGOUT_USER_ACTION: 'LOGOUT_USER_ACTION',
    CHANGE_AUTH_STATUS: 'CHANGE_AUTH_STATUS',
}