export const USER_MANAGEMENT_REDUX_CONSTANTS = {
    LOAD_USERS: 'LOAD_USERS',
    ON_CHANGE_USER_FORM_INPUTS: 'ON_CHANGE_USER_FORM_INPUTS',
    ON_RESET_USER_DETAIL_FORM: 'ON_RESET_USER_DETAIL_FORM',
    ON_ADD_USER_DETAIL_FORM: 'ON_ADD_USER_DETAIL_FORM',
    ON_DELETE_USER_RECORD: 'ON_DELETE_USER_RECORD',
}

export {}